package br.edu.uepb.cg.panels;

import br.edu.uepb.cg.enums.FiltrosEnum;
import javax.swing.JRadioButton;

/**
 * Representa o menu para manipulação da circunferência
 *
 * @author Douglas Rafael
 */
public class PanelMenuFiltros extends javax.swing.JPanel {

    private static PanelMenuFiltros instance;
    private FiltrosEnum tipoAlgoritimo;

    public static synchronized PanelMenuFiltros getInstance() {
        if (instance == null) {
            instance = new PanelMenuFiltros();
        }
        return instance;
    }

    /**
     * Construtor
     */
    private PanelMenuFiltros() {
        initComponents();
        panelDados.setVisible(false);
    }

    public FiltrosEnum getTipoAlgoritimo() {
        if (rbAltoReforco.isSelected()) {
            setTipoAlgoritimo(FiltrosEnum.ALTO_REFORCO);
        } 
        
        return tipoAlgoritimo;
    }

    public void setTipoAlgoritimo(FiltrosEnum tipoAlgoritimo) {
        this.tipoAlgoritimo = tipoAlgoritimo;
    }
    
    public double getA() {
        return (double) valorA.getValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFiltros = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        rbAltoReforco = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        panelDados = new javax.swing.JPanel();
        valorA = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(240, 32767));
        setMinimumSize(new java.awt.Dimension(240, 0));
        setPreferredSize(new java.awt.Dimension(240, 779));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        buttonGroupFiltros.add(rbAltoReforco);
        rbAltoReforco.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rbAltoReforco.setText("Alto Reforço (Hight-Boost)");
        rbAltoReforco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosSelect(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAltoReforco)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAltoReforco)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        panelDados.setMaximumSize(new java.awt.Dimension(220, 80));
        panelDados.setMinimumSize(new java.awt.Dimension(220, 80));

        valorA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        valorA.setModel(new javax.swing.SpinnerNumberModel(1.5d, null, null, 1.0d));
        valorA.setMaximumSize(new java.awt.Dimension(30, 25));
        valorA.setMinimumSize(new java.awt.Dimension(30, 25));
        valorA.setPreferredSize(new java.awt.Dimension(30, 25));

        jLabel1.setText("Valor de A:");

        javax.swing.GroupLayout panelDadosLayout = new javax.swing.GroupLayout(panelDados);
        panelDados.setLayout(panelDadosLayout);
        panelDadosLayout.setHorizontalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDadosLayout.setVerticalGroup(
            panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filtrosSelect(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosSelect
        JRadioButton radio = (JRadioButton) evt.getSource();
        PanelFiltros.getInstance().setTitle("Filtro de " + radio.getText());

        if (rbAltoReforco.isSelected()) {
            panelDados.setVisible(true);
        } else {
            panelDados.setVisible(false);
        }
    }//GEN-LAST:event_filtrosSelect


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDados;
    private javax.swing.JRadioButton rbAltoReforco;
    private javax.swing.JSpinner valorA;
    // End of variables declaration//GEN-END:variables
}
